apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ogplatform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://appuser:ZIDirPhKsMpTK0oQ8xpS@ogplatform-db.cxs2iq2cugp5.eu-west-1.rds.amazonaws.com:5432/appdb"
