apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ogplatform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://appuser:gCG2PE3ne4PD40WhPLId@ogplatform-pg.postgres.database.azure.com:5432/appdb?sslmode=require"
